[package]
name = "doppler-keygen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "doppler-keygen"
path = "src/main.rs"

[dependencies]
bs58 = "0.5.1"
solana-keypair = "2.2.1"
solana-signer = "2.2.1"
hex = "0.4.3"
serde_json = "1.0"

[profile.release]
lto = true
codegen-units = 1